######################################################################
#
# File name : tb_top_simulate.do
# Created on: Thu Mar 28 12:47:03 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_top_wave.do}

view wave
view structure
view signals

do {tb_top.udo}

run 1000ns
