######################################################################
#
# File name : tb_top_compile.do
# Created on: Thu Mar 28 12:47:01 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_2020.4\\win64\\vlib modelsim_lib/work
D:\\modelsim_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modelsim_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_2020.4\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../data_gen.srcs/sources_1/ip/clk_wiz_0" \
"../../../../data_gen.srcs/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../data_gen.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../../data_gen.srcs/sources_1/new/gen_uart_data.v" \
"../../../../data_gen.srcs/sources_1/new/top.v" \
"../../../../data_gen.srcs/sources_1/new/uart_tx.v" \
"../../../../data_gen.srcs/sim_1/new/tb_top.v" \


# compile glbl module
D:\\modelsim_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

