######################################################################
#
# File name : tb_top_wave.do
# Created on: Wed Mar 20 14:13:05 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
